name: Demo CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 23f2003857@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"

      - name: Show date
        run: date
